INSERT INTO USERS(ID, NAME, EMAIL, EMAILVERIFIED, PASSWORD, AUTHPROVIDER) VALUES (0, 'Ivan', 'ivan@gmail.com', 'test', 'test', 'test');

INSERT INTO TASKS(ID, TEXT, DONE) VALUES (0, 'test task A', FALSE);
INSERT INTO TASKS(ID, TEXT, DONE) VALUES (1, 'test task B', FALSE);